# Generated by Django 6.0.4 on 2026-04-17 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(choices=[('owl', 'Owl'), ('fox', 'Fox'), ('bear', 'Bear'), ('cat', 'Cat'), ('dog', 'Dog'), ('rabbit', 'Rabbit'), ('penguin', 'Penguin'), ('butterfly', 'Butterfly'), ('star', 'Star'), ('flame', 'Fire'), ('lightning', 'Lightning'), ('rocket', 'Rocket'), ('planet', 'Planet'), ('diamond', 'Diamond'), ('crown', 'Crown'), ('heart', 'Heart')], default='owl', help_text='Selected avatar identifier.', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('uz', "O'zbek")], default='ru', help_text='Preferred interface language.', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
