# Generated by Django 4.2.29 on 2026-04-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_avatar',
            field=models.ImageField(blank=True, help_text='User uploaded custom avatar.', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(choices=[('owl', 'Owl'), ('fox', 'Fox'), ('custom', 'Custom'), ('cat', 'Cat'), ('dog', 'Dog'), ('rabbit', 'Rabbit'), ('penguin', 'Penguin'), ('butterfly', 'Butterfly'), ('star', 'Star'), ('flame', 'Fire'), ('lightning', 'Lightning'), ('rocket', 'Rocket'), ('planet', 'Planet'), ('diamond', 'Diamond'), ('crown', 'Crown'), ('heart', 'Heart')], default='owl', help_text='Selected avatar identifier.', max_length=20),
        ),
    ]
