# Generated by Django 4.2.29 on 2026-04-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_custom_avatar_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(choices=[('owl', 'Owl'), ('fox', 'Fox'), ('cat', 'Cat'), ('dog', 'Dog'), ('rabbit', 'Rabbit'), ('penguin', 'Penguin'), ('butterfly', 'Butterfly'), ('star', 'Star'), ('flame', 'Fire'), ('lightning', 'Lightning'), ('rocket', 'Rocket'), ('planet', 'Planet'), ('diamond', 'Diamond'), ('crown', 'Crown'), ('heart', 'Heart'), ('custom', 'Custom')], default='owl', help_text='Selected avatar identifier.', max_length=20),
        ),
    ]
