# Generated by Django 4.2.29 on 2026-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='Дата последней активности (для сброса счетчика мини-экзаменов).', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_streak_date',
            field=models.DateField(blank=True, help_text='Дата последнего обновления стрика.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mini_exams_today',
            field=models.PositiveIntegerField(default=0, help_text='Количество пройденных мини-экзаменов за сегодня.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_days',
            field=models.PositiveIntegerField(default=0, help_text='Текущий стрик (ударные дни).'),
        ),
    ]
