# Generated by Django 4.2.29 on 2026-04-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_last_activity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_days_history',
            field=models.JSONField(blank=True, default=list, help_text='История ударных дней (список дат YYYY-MM-DD).'),
        ),
    ]
