# Generated by Django 4.2.29 on 2026-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_active_days_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='streak_goal',
            field=models.PositiveIntegerField(default=7, help_text='Цель ударных дней.'),
        ),
    ]
