# Generated by Django 6.0.4 on 2026-05-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_migrate_mentors_group_to_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('sysmentor', 'SysMentor')], default='student', help_text='Роль пользователя: student или mentor.', max_length=10),
        ),
    ]
