# Generated by Django 4.2.29 on 2026-04-11 16:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('instructions', models.TextField(blank=True, help_text='Part instructions extracted via OCR or entered manually.')),
                ('audio_file', models.FileField(help_text='MP3 audio for this part.', upload_to='exams/audio/')),
                ('question_image', models.ImageField(blank=True, help_text='Original screenshot of the questions (always shown to users).', upload_to='exams/questions/')),
                ('map_image', models.ImageField(blank=True, help_text='Supplementary image (e.g. map for Part 4).', null=True, upload_to='exams/maps/')),
                ('points_per_question', models.FloatField(default=2.0, help_text='Weighted points awarded per correct answer in this part.')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(help_text='Sequential number within this part (1, 2, 3…).')),
                ('global_question_number', models.PositiveIntegerField(blank=True, help_text='Question number as printed on the exam paper (1–35).', null=True)),
                ('question_text', models.TextField(blank=True, help_text='OCR-extracted question text. The original image is the primary display.')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('map_label', 'Map Labeling')], max_length=20)),
                ('correct_answer', models.CharField(help_text='The correct answer: a letter (A/B/C…) or a word/phrase.', max_length=200)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.part')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('part', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('test_type', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading')], default='listening', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active tests are shown to users.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0, help_text='Weighted total score across all parts.')),
                ('max_possible_score', models.FloatField(default=0.0, help_text='Maximum achievable weighted score.')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='exams.test'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.userattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='exams.question')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('test', 'part_number')},
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Option letter: A, B, C, etc.', max_length=5)),
                ('text', models.CharField(help_text='The text of this answer option.', max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('question', 'label')},
            },
        ),
    ]
