# Generated by Django 4.2.29 on 2026-04-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='passage_text',
            field=models.TextField(blank=True, help_text='Full passage text with numbered blanks (Parts 2 & 6). Blanks are marked as {30}, {31}, etc.'),
        ),
        migrations.AddField(
            model_name='part',
            name='passage_title',
            field=models.CharField(blank=True, help_text="Title of the passage (Parts 2 & 6), e.g. 'British Marine Life in Crisis'.", max_length=300),
        ),
        migrations.AddField(
            model_name='part',
            name='shared_choices_json',
            field=models.JSONField(blank=True, default=list, help_text='Shared choices for matching parts (e.g. Part 3). Format: [{"label": "A", "text": "disturbing someone"}, ...]'),
        ),
        migrations.AddField(
            model_name='question',
            name='group_label',
            field=models.CharField(blank=True, help_text="Sub-group label, e.g. 'Extract One' (Part 5) or 'Speaker 1' (Part 3).", max_length=100),
        ),
    ]
