# Generated by Django 4.2.29 on 2026-04-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_part_passage_text_part_passage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='transcript',
            field=models.TextField(blank=True, help_text='AI-generated audio transcript.'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='AI-generated explanation for the correct answer.'),
        ),
    ]
