# Generated by Django 4.2.29 on 2026-04-16 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_part_transcript_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The mentor who created/uploaded this test.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
