# Generated by Django 4.2.29 on 2026-04-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_test_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('informal', 'Informal Message (Task 1.1)'), ('formal', 'Formal Letter (Task 1.2)'), ('essay', 'Academic Essay (Task 2)')], max_length=20)),
                ('input_text', models.TextField(blank=True, help_text='The incoming letter, advert, or text the student reads.')),
                ('prompt', models.TextField(help_text='The instructions/prompt for writing.')),
                ('min_words', models.PositiveIntegerField(default=0)),
                ('max_words', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order in the test (1, 2, or 3)')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to='exams.test')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_text', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('is_graded', models.BooleanField(default=False)),
                ('estimated_level', models.CharField(blank=True, help_text='CEFR level estimate (A1-C1)', max_length=10)),
                ('feedback_text', models.TextField(blank=True, help_text='General feedback on structure and grammar')),
                ('corrections_json', models.JSONField(blank=True, default=list, help_text='List of correction dicts: {original, correction, explanation}')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to='exams.userattempt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.writingtask')),
            ],
            options={
                'unique_together': {('attempt', 'task')},
            },
        ),
    ]
