# Generated by Django 4.2.29 on 2026-04-19 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_writingtask_writingsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabBlurEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='How long (seconds) the student was away from the tab.', null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_blur_events', to='exams.userattempt')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AutoSaveDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='Draft answers: {"question_<id>": "A", "task_<id>": "text", ...}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='exams.userattempt')),
            ],
        ),
    ]
