# Generated by Django 6.0.4 on 2026-04-19 13:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_tabblurevent_autosavedraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField(help_text='Part number as printed on the exam (1–5 typically).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('instruction', models.TextField(blank=True, help_text="Full instruction text for this part (e.g. 'Fill in each gap with ONE word...').")),
                ('question_number_start', models.PositiveIntegerField(blank=True, help_text='First question number in this part (e.g. 1 for Q1-6).', null=True)),
                ('question_number_end', models.PositiveIntegerField(blank=True, help_text='Last question number in this part (e.g. 6 for Q1-6).', null=True)),
                ('test', models.ForeignKey(limit_choices_to={'test_type': 'reading'}, on_delete=django.db.models.deletion.CASCADE, related_name='reading_parts', to='exams.test')),
            ],
            options={
                'ordering': ['part_number'],
                'unique_together': {('test', 'part_number')},
            },
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Title of the passage (e.g. 'Sepsis', 'Radio Automation').", max_length=300)),
                ('content', models.TextField(help_text="Full concatenated passage text. Page numbers and footers removed. Paragraphs separated by '\\n\\n'. Fill-in-the-blank gaps are marked as [GAP].")),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passage', to='exams.readingpart')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_parts', models.PositiveIntegerField(default=5, help_text='Number of parts in this reading test (typically 5).')),
                ('test', models.OneToOneField(limit_choices_to={'test_type': 'reading'}, on_delete=django.db.models.deletion.CASCADE, related_name='reading_meta', to='exams.test')),
            ],
            options={
                'verbose_name': 'Reading Test Metadata',
                'verbose_name_plural': 'Reading Tests Metadata',
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(help_text='Global question number as printed on the exam paper (e.g. 1, 7, 21).')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_in_the_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('true_false_ni', 'True / False / No Information'), ('insert_sentence', 'Insert Sentence')], max_length=25)),
                ('question_text', models.TextField(blank=True, help_text="The question stem or statement. For fill_in_the_blank, the sentence with [GAP] as the placeholder. For matching, e.g. 'Text 7' or the full statement to match.")),
                ('options', models.JSONField(blank=True, default=list, help_text="Answer options as a list of strings. For multiple_choice: ['A) text...', 'B) text...', 'C) text...', 'D) text...']. For matching: the shared list of statements (A-J). Empty [] for fill_in_the_blank with no provided choices.")),
                ('correct_answer', models.CharField(help_text="The correct answer. A letter for MCQ/matching ('A', 'C', 'H'). A word or phrase for fill_in_the_blank ('killers'). 'True', 'False', or 'No Information' for true_false_ni.", max_length=500)),
                ('explanation', models.TextField(blank=True, help_text='Optional AI-generated explanation for why this answer is correct.')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.readingpart')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('part', 'question_number')},
            },
        ),
    ]
