# Generated by Django 6.0.4 on 2026-04-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_readinguseranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the test was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-deleted tests are hidden everywhere but preserve attempt history.'),
        ),
    ]
