# Generated by Django 6.0.4 on 2026-04-21 05:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_test_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('instructions', models.TextField(blank=True)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='exams/speaking/original/')),
                ('cropped_image', models.ImageField(blank=True, help_text='Isolated image for this part (e.g. Part 2 cue card or Part 3 charts).', null=True, upload_to='exams/speaking/cropped/')),
                ('alt_text', models.TextField(blank=True, help_text='AI-generated description of the image for accessibility and low-bandwidth fallback.')),
                ('validation_data', models.JSONField(blank=True, default=dict, help_text='Stores bounding boxes and raw extraction data from Document AI / Gemini.')),
                ('is_validated', models.BooleanField(default=False, help_text='Has the mentor validated the auto-crop and extraction?')),
                ('test', models.ForeignKey(limit_choices_to={'test_type': 'speaking'}, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_parts', to='exams.test')),
            ],
            options={
                'ordering': ['part_number'],
                'unique_together': {('test', 'part_number')},
            },
        ),
        migrations.CreateModel(
            name='SpeakingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('question_text', models.TextField(help_text='Text of the question, string for TTS generation.')),
                ('audio_file', models.FileField(blank=True, help_text='Pre-generated TTS audio for this question.', null=True, upload_to='exams/speaking/audio/')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.speakingpart')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('part', 'question_number')},
            },
        ),
    ]
