# Generated by Django 4.2.29 on 2026-04-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_speakingpart_speakingquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='uploads/speaking/')),
                ('duration_seconds', models.FloatField(default=0)),
                ('transcript', models.TextField(blank=True)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('estimated_level', models.CharField(blank=True, max_length=5)),
                ('feedback_text', models.TextField(blank=True)),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_submissions', to='exams.userattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.speakingquestion')),
            ],
            options={
                'ordering': ['question__part__part_number', 'question__question_number'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
