# Generated by Django 4.2.29 on 2026-04-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_speaking_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingpart',
            name='debate_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores Part 3 debate table: {"topic": "...", "for_points": [...], "against_points": [...]}'),
        ),
    ]
