# Generated by Django 6.0.4 on 2026-04-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_speaking_debate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingpart',
            name='points_per_question',
            field=models.FloatField(default=10.0, help_text='Max weighted points per question in this part (auto-set by part number).'),
        ),
    ]
