# Generated by Django 6.0.4 on 2026-04-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_speaking_part_points_per_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingsubmission',
            name='feedback_json',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual feedback: {"en": "...", "ru": "...", "uz": "..."}'),
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='feedback_json',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual feedback: {"en": "...", "ru": "...", "uz": "..."}'),
        ),
        migrations.AlterField(
            model_name='writingsubmission',
            name='corrections_json',
            field=models.JSONField(blank=True, default=list, help_text='List of correction dicts: {original, correction, explanation, explanation_i18n}'),
        ),
    ]
