# Generated by Django 4.2.29 on 2026-04-27 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0017_ai_chat_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, help_text='Normalised lowercase English word or short phrase.', max_length=100, unique=True)),
                ('transcription', models.CharField(blank=True, help_text='IPA phonetic transcription, e.g. /juːˈbɪkwɪtəs/.', max_length=200)),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Translations keyed by language code: {"ru": "...", "uz": "...", "en": "..."}.')),
                ('definition', models.TextField(blank=True, help_text='English definition / meaning.')),
                ('example', models.TextField(blank=True, help_text='Example sentence using the word in natural context.')),
                ('part_of_speech', models.CharField(blank=True, help_text='Part of speech: noun, verb, adjective, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Word Cache',
                'verbose_name_plural': 'Word Cache',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual input'), ('dblclick', 'Double-click in UI'), ('test', 'From a test')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cached_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to='exams.wordcache')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'cached_word')},
            },
        ),
    ]
