# Generated by Django 4.2.29 on 2026-04-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_wordcache_dictionaryentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordcache',
            name='definition',
        ),
        migrations.AddField(
            model_name='wordcache',
            name='definitions',
            field=models.JSONField(blank=True, default=dict, help_text='Definitions keyed by language code: {"ru": "...", "uz": "...", "en": "..."}.'),
        ),
    ]
