# Generated by Django 6.0.4 on 2026-04-28 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_remove_wordcache_definition_wordcache_definitions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(db_index=True, help_text="YouTube video ID (e.g. 'dQw4w9WgXcQ').", max_length=20, unique=True)),
                ('title', models.CharField(help_text='Video title (fetched from YouTube or entered manually).', max_length=300)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], default='B2', help_text='Target CEFR level for quiz question generation.', max_length=2)),
                ('thumbnail_url', models.URLField(blank=True, help_text='YouTube video thumbnail URL.')),
                ('transcript_json', models.JSONField(blank=True, default=list, help_text='Raw transcript from youtube-transcript-api. Format: [{"text": "...", "start": 0.0, "duration": 3.5}, ...]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who added this video lesson.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_time_seconds', models.PositiveIntegerField(help_text='Time in seconds when the video should pause for this question.')),
                ('question_text', models.TextField(help_text='The listening comprehension question.')),
                ('options', models.JSONField(default=list, help_text='Answer options as a list of strings: ["opt A", "opt B", "opt C", "opt D"].')),
                ('correct_option_index', models.PositiveSmallIntegerField(help_text='0-based index of the correct answer in the options list.')),
                ('explanation', models.TextField(blank=True, help_text='AI-generated explanation of why the correct answer is right.')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='exams.videolesson')),
            ],
            options={
                'ordering': ['trigger_time_seconds'],
            },
        ),
    ]
