# Generated by Django 6.0.4 on 2026-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_videoroom_videoroomparticipant_videoroomanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='topic_tags',
            field=models.JSONField(blank=True, default=list, help_text='AI-detected topic categories for this video, e.g. ["Science", "Technology", "Education"].'),
        ),
    ]
