# Generated by Django 6.0.4 on 2026-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_add_topic_tags_to_videolesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcache',
            name='alternative_form',
            field=models.TextField(blank=True, default='', help_text='Opposite-register equivalent: informal→formal or formal→informal.'),
        ),
        migrations.AddField(
            model_name='wordcache',
            name='register',
            field=models.CharField(blank=True, default='', help_text='Register: formal, informal, or neutral.', max_length=20),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='cefr_level',
            field=models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced')], default='B2', help_text='Target CEFR level for quiz question generation.', max_length=2),
        ),
    ]
