# Generated by Django 6.0.4 on 2026-05-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_wordcache_register_alternative_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
