# Generated by Django 4.2.29 on 2026-05-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0025_remove_unique_from_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='clone_of',
            field=models.ForeignKey(blank=True, help_text='The original test this was cloned from (set by split_parts).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_tests', to='exams.test'),
        ),
    ]
