# Generated by Django 4.2.29 on 2026-05-02 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exams.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0026_add_clone_of_to_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название класса (например, 'B2 Утренняя группа').", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Описание класса.')),
                ('join_code', models.CharField(db_index=True, default=exams.models._generate_join_code, help_text='Уникальный код для вступления учеников.', max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные классы скрыты от учеников.')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentored_classrooms', to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(blank=True, help_text='Тесты, назначенные этому классу.', related_name='classrooms', to='exams.test')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='exams.classroom')),
                ('student', models.OneToOneField(help_text='Каждый ученик может быть только в одном классе.', on_delete=django.db.models.deletion.CASCADE, related_name='classroom_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
    ]
