# Generated by Django 4.2.29 on 2026-05-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0027_add_classroom_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='video_lessons',
            field=models.ManyToManyField(blank=True, help_text='Видеоуроки, назначенные этому классу.', related_name='classrooms', to='exams.videolesson'),
        ),
    ]
