# Generated by Django 6.0.4 on 2026-05-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0029_test_is_class_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingsubmission',
            name='mentor_feedback',
            field=models.TextField(blank=True, help_text='Written feedback from the mentor.'),
        ),
        migrations.AddField(
            model_name='speakingsubmission',
            name='mentor_score',
            field=models.FloatField(blank=True, help_text='Manual score set by a mentor (0–10).', null=True),
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='mentor_feedback',
            field=models.TextField(blank=True, help_text='Written feedback from the mentor.'),
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='mentor_score',
            field=models.FloatField(blank=True, help_text='Manual score set by a mentor (0–10 for speaking, 0–100 for writing).', null=True),
        ),
    ]
