# Generated by Django 4.2.29 on 2026-05-03 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0030_add_mentor_score_to_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('gold', 'Gold'), ('red', 'Red'), ('teal', 'Teal')], default='blue', help_text='Цветовой акцент карточки класса.', max_length=20),
        ),
        migrations.AddField(
            model_name='classroom',
            name='emoji',
            field=models.CharField(blank=True, default='🎓', help_text='Эмодзи для визуальной идентификации класса.', max_length=8),
        ),
        migrations.CreateModel(
            name='ClassroomAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Закреплённые объявления отображаются первыми.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_announcements', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='exams.classroom')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
