# Generated by Django 4.2.29 on 2026-05-03 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def generate_unique_invite_tokens(apps, schema_editor):
    """Populate invite_token with unique UUIDs for existing classrooms."""
    Classroom = apps.get_model('exams', 'Classroom')
    for classroom in Classroom.objects.all():
        classroom.invite_token = uuid.uuid4()
        classroom.save(update_fields=['invite_token'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0031_classroom_enhancements'),
    ]

    operations = [
        # Step 1: Add invite_token without unique constraint
        migrations.AddField(
            model_name='classroom',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID-токен для пригласительных ссылок.', null=True),
        ),
        # Step 2: Populate unique UUIDs for existing rows
        migrations.RunPython(generate_unique_invite_tokens, migrations.RunPython.noop),
        # Step 3: Add unique + db_index constraints, remove null
        migrations.AlterField(
            model_name='classroom',
            name='invite_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='UUID-токен для пригласительных ссылок.', unique=True),
        ),
        # Multi-classroom: OneToOneField → ForeignKey
        migrations.AlterField(
            model_name='classroommembership',
            name='student',
            field=models.ForeignKey(help_text='Ученик может состоять в нескольких классах.', on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classroommembership',
            unique_together={('classroom', 'student')},
        ),
        # New models
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment', 'Новое задание'), ('announcement', 'Объявление'), ('grade', 'Оценка выставлена'), ('deadline', 'Напоминание о дедлайне')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, help_text='URL для перехода при клике.', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Необязательное название задания (напр. 'Домашка неделя 3').", max_length=300)),
                ('instructions', models.TextField(blank=True, help_text='Инструкции ментора к заданию.')),
                ('due_date', models.DateTimeField(blank=True, help_text='Дедлайн. NULL = без ограничения по времени.', null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Обязательное задание или дополнительное.')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.classroom')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.test')),
                ('video_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.videolesson')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
